### ISSUE TITLE
Niggli cell vs primitive cell kpoints in tetragonal body-centered lattice

### ISSUE THREAD

**Issue by bmondal94** [msg-byu/autoGR#37]
I am having problem understanding the appropriate KPOINTS file for tetragonal body-centered lattice. The irreducible k-points file (IBZKPT) generated using the primitive cell in VASP (wiki/index.php/KPOINTS#generalized_regular_grids) contains the weight of 4 for the Gamma point. When I use the same primitive cell POSCAR in autoGR it gives me the k-points with one of the k-point coordinates>0.5. But we should not have k-point coordinates greater than 0.5 in the reciprocal space,  because there are no k-point coordinates greater than 0.5 in the body-centered tetragonal lattice Brillouin zone high symmetry path.  If I use the Niggli cell POSCAR in autoGR it generates different k-points. So, I am not sure which one is the right way to go in VASP. May I ask for suggestions, please? [Just for the info: the issue was also posted in the vasp forum (https://www.vasp.at/forum/viewtopic.php?f=4&t=18273)]
[All_Files.zip](https://github.com/msg-byu/autoGR/files/7884655/All_Files.zip)

**Comment by bmondal94** [comment]
!!!!
> I'll take a look at this. Please ping me again next week if you don't hear from me. Very, very busy back-to-back semesters. Gus Hart Professor, Physics and Astronomy http://msg.byu.edu
> […](#)

**Comment by glwhart** [comment]
Teaching is really demanding this semester. I'll be working hard on all the
github issues on all my repos as soon as the semester ends.

Gus Hart
Professor, Physics and Astronomy
http://msg.byu.edu

**Comment by glwhart** [comment]
I just fixed another issue, so I'm finally looking at this.

**Comment by glwhart** [comment]
Some comments:

1) VASP uses Monkhorst-Pack grids, i.e. "regular grids" (each recip lattice vector is divided into an integer number of parts). But autoGR uses *generalized* regular grids. The grid generating vectors create a kpoint lattice that is *commensurate* with the reciprocal cell, but the generating vectors are not necessarily in the same directions as the recip lattice vectors. So there is no expectation that VASP's grids and autoGR grids will be the same. Typically, they won't be. (See attachment)

2) Even though VASP weights the gamma point more than 1 (in some cases, depending on the crystal structure) the relative weights are correct. I'm not sure what the convention is, but when I have checked the grids by hand, the relative weighting was correct, even if the gamma point was not weighted as 1.

3) It's possible for kpoints to have lattice coordinates with magnitude greater that 0.5 depending on the choice of reciprocal lattice vectors (which depend on the choice of real space lattice vectors) and still be inside the first BZ. Points will necessarily have lattice coordinates with magnitude less than 0.5 only when the recip lattice vectors are the so-called Minkowski-reduced vectors---the shortest basis vectors possible. autoGR uses a Minkowski-reduced basis internally but expresses the final KPOINT set in terms of the recip lattice vectors that the user chose (via their choice of real-space vectors).

4) Different choices of real-space vectors lead to different reciprocal lattice vectors and thus to different representations of the grids generated by autoGR. It should make no difference in your calculations since internally the best grid is chosen irrespective of the basis choice.

5) Vasp may fold the kpoints differently (but equivalently) to autoGR so the list generated by vasp from autoGR.gen may *look* different from the autoGR list, but they should be equivalent.

![graphical-abstract-kpoints-autoGR](https://user-images.githubusercontent.com/7816856/196521298-ec36604b-7606-49b0-af43-de01b6004ad2.png)

I hope this helps.

**Comment by bmondal94** [comment]
Many many thanks for the clarifications. Nice explanations. I personally enjoyed them.
